### ISSUE TITLE
astp: remove conv functions

### ISSUE THREAD

**Issue by fexolm** [cristaloleg/astp#4]
I think, conv functions has no advantages over `n: = n. (* Ast.Stmt) ` syntaxis. And the case, where we want to panic after unsuccessful cast is not clear to me.
So, maybe remove them and leave just predicates there? Or you know usecases, where conv functions could be useful?

**Comment by quasilyte** [comment]
I think what @fexolm is meant is that `x.(*Type)` without `comma-ok` value will panic just as any conv functions from `astp` package:
```go
// Panics if expr is not *ast.ParenExpr, can be used as expression
paren := expr.(*ast.ParenExpr)
// Does not panic, can't be used as expression
paren, ok := expr.(*ast.ParenExpr)

// conv functions are not shorted either:
expr.(*ast.ParenExpr)
astp.AsParenExpr(expr)
```
The only case I can think of is passing conversion func as callback, but I've never seen such necessity.
Predicates, on the other hand, usually very useful for callbacks.

**Comment by cristaloleg** [comment]
@fexolm yep, `AsXXX` was created for this case:
```
// I know that `expr` is XXX, so...
fun(astp.AsXXX(expr))
```

**Comment by quasilyte** [comment]
Yeah, that's understandable, the question is, why you need a function for that?
```go
// I know that `expr` is XXX, so...
sad(expr.(XXX))
```

**Comment by cristaloleg** [comment]
Why not? :D 
(ok, I'm kidding, it's quite useless)
